import { useCallback, useEffect, useRef, useState, type CSSProperties } from "react";
import { createPortal } from "react-dom";
import { listAssets, mediaUrl, type AssetItem } from "../api/client";
import { IconClose, IconRefresh, IconSpinner, IconUpload } from "../canvas/icons";

/**
 * Media picker — the modal behind every "Replace" / "Upload" affordance on
 * a node.
 *
 *   LEFT  — every image the agent has ever seen (uploaded by the user OR
 *           generated by Flow), newest first, from `GET /api/assets`.
 *           One click reuses it immediately: no upload round-trip, no
 *           re-push to Flow — the media id is already a Flow media id.
 *   RIGHT — the classic "bring a new file" panel: click-to-browse or
 *           drag-and-drop.
 *
 * The list is cached module-side so reopening the picker paints instantly;
 * a background revalidation keeps it fresh. That cache is the whole point
 * of the component — picking an existing image should feel free.
 *
 * Rendered through a portal: React Flow's viewport sets a CSS `transform`,
 * which would otherwise become the containing block for `position: fixed`
 * and trap the overlay inside the canvas.
 */

const ACCEPT_MIME = "image/png,image/jpeg,image/webp,image/gif";

/**
 * Mirrors `agent/flowboard/routes/upload.py::_classify_aspect` so a reused
 * image lands with the same `aspectRatio` an upload would have produced —
 * the node frame and the downstream gen-dialog both key off it.
 */
export function classifyAspect(width: number, height: number): string {
  if (width <= 0 || height <= 0) return "IMAGE_ASPECT_RATIO_LANDSCAPE";
  const ratio = width / height;
  if (ratio >= 0.91 && ratio <= 1.1) return "IMAGE_ASPECT_RATIO_SQUARE";
  if (ratio > 1.1) return "IMAGE_ASPECT_RATIO_LANDSCAPE";
  return "IMAGE_ASPECT_RATIO_PORTRAIT";
}

// Survives unmount so the second open is instant. Refreshed in the
// background on every open, and after each successful upload.
let assetCache: AssetItem[] | null = null;

export function invalidateMediaPickerCache(): void {
  assetCache = null;
}

interface Props {
  /** Called on backdrop click, ✕, or Esc. */
  onClose(): void;
  /** A library tile was clicked — reuse this media id right away. */
  onPickExisting(mediaId: string, aspectRatio?: string): void;
  /** A new file arrived (browse or drop). Resolve `false` to keep the modal open. */
  onUploadFile(file: File): Promise<boolean> | boolean | void;
  /** True while the parent node is mid-upload. */
  uploading?: boolean;
  /** Highlighted in the grid as "đang dùng". */
  currentMediaId?: string;
  title?: string;
}

export function MediaPickerModal({
  onClose,
  onPickExisting,
  onUploadFile,
  uploading = false,
  currentMediaId,
  title = "Chọn ảnh",
}: Props) {
  const [items, setItems] = useState<AssetItem[] | null>(assetCache);
  const [error, setError] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  // naturalWidth/Height harvested from each <img> once it decodes, so a
  // pick can classify the aspect without a second network call.
  const dimsRef = useRef<Record<string, [number, number]>>({});
  const fileInputRef = useRef<HTMLInputElement>(null);

  const load = useCallback(async () => {
    setRefreshing(true);
    setError(null);
    try {
      const rows = await listAssets("image", 500);
      assetCache = rows;
      setItems(rows);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  // Esc closes. Bound on document so it works no matter what has focus.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") {
        e.stopPropagation();
        onClose();
      }
    }
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  async function handleFile(file: File) {
    const ok = await onUploadFile(file);
    // A handler that returns nothing is treated as success — only an
    // explicit `false` keeps the modal open so the error stays readable.
    if (ok !== false) {
      assetCache = null;
      onClose();
    }
  }

  function pick(item: AssetItem) {
    const dims = dimsRef.current[item.media_id];
    onPickExisting(item.media_id, dims ? classifyAspect(dims[0], dims[1]) : undefined);
  }

  const count = items?.length ?? 0;

  return createPortal(
    <div
      role="dialog"
      aria-modal="true"
      aria-label={title}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 2147483646,
        background: "rgba(10, 10, 12, 0.86)",
        backdropFilter: "blur(6px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 24,
        fontFamily: "inherit",
        color: "var(--fg-1, #e3e3e3)",
      }}
    >
      <div
        style={{
          display: "flex",
          gap: 16,
          width: "min(1180px, 96vw)",
          height: "min(760px, 88vh)",
        }}
      >
        {/* ── LEFT: library ─────────────────────────────────────────── */}
        <section
          style={{
            flex: 1,
            minWidth: 0,
            display: "flex",
            flexDirection: "column",
            background: "#141416",
            border: "1px solid rgba(255,255,255,0.09)",
            borderRadius: 14,
            overflow: "hidden",
          }}
        >
          <header
            style={{
              display: "flex",
              alignItems: "center",
              gap: 10,
              padding: "14px 16px",
              borderBottom: "1px solid rgba(255,255,255,0.07)",
            }}
          >
            <span style={{ fontSize: 15, fontWeight: 600, color: "var(--fg-0, #f5f5f5)" }}>
              Thư viện
            </span>
            <span style={{ fontSize: 12, opacity: 0.55 }}>
              {items === null ? "đang tải…" : `${count} ảnh`}
            </span>
            <span style={{ flex: 1 }} />
            <button
              type="button"
              onClick={() => void load()}
              title="Làm mới"
              aria-label="Làm mới"
              disabled={refreshing}
              style={iconBtn(refreshing)}
            >
              {refreshing ? <IconSpinner size={14} /> : <IconRefresh size={14} />}
            </button>
          </header>

          <div style={{ flex: 1, overflowY: "auto", padding: 14 }}>
            {error && (
              <p style={{ margin: 0, padding: 12, fontSize: 13, color: "#ff8a80" }}>
                ✗ {error}
              </p>
            )}
            {items === null && !error && (
              <p style={{ margin: 0, padding: 12, fontSize: 13, opacity: 0.6 }}>
                Đang tải thư viện…
              </p>
            )}
            {items !== null && count === 0 && !error && (
              <p style={{ margin: 0, padding: 12, fontSize: 13, opacity: 0.6 }}>
                Chưa có ảnh nào. Upload một ảnh ở panel bên phải để bắt đầu.
              </p>
            )}

            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fill, minmax(118px, 1fr))",
                gap: 8,
              }}
            >
              {(items ?? []).map((item) => {
                const isCurrent = item.media_id === currentMediaId;
                return (
                  <button
                    key={item.id}
                    type="button"
                    onClick={() => pick(item)}
                    title={isCurrent ? "Ảnh đang dùng" : "Dùng ảnh này"}
                    style={{
                      position: "relative",
                      aspectRatio: "1 / 1",
                      padding: 0,
                      overflow: "hidden",
                      borderRadius: 10,
                      cursor: "pointer",
                      background: "#1c1c1f",
                      border: isCurrent
                        ? "2px solid #7c6cff"
                        : "1px solid rgba(255,255,255,0.08)",
                    }}
                  >
                    <img
                      src={mediaUrl(item.media_id)}
                      alt=""
                      loading="lazy"
                      onLoad={(e) => {
                        const el = e.currentTarget;
                        dimsRef.current[item.media_id] = [
                          el.naturalWidth,
                          el.naturalHeight,
                        ];
                      }}
                      style={{
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                        display: "block",
                      }}
                    />
                    {isCurrent && (
                      <span
                        style={{
                          position: "absolute",
                          left: 6,
                          bottom: 6,
                          padding: "2px 6px",
                          borderRadius: 6,
                          fontSize: 10,
                          background: "rgba(124,108,255,0.9)",
                          color: "#fff",
                        }}
                      >
                        đang dùng
                      </span>
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        </section>

        {/* ── RIGHT: upload ─────────────────────────────────────────── */}
        <section
          onDragOver={(e) => {
            e.preventDefault();
            if (!dragOver) setDragOver(true);
          }}
          onDragLeave={(e) => {
            e.preventDefault();
            setDragOver(false);
          }}
          onDrop={(e) => {
            e.preventDefault();
            setDragOver(false);
            const f = e.dataTransfer.files?.[0];
            if (f) void handleFile(f);
          }}
          style={{
            width: 320,
            flexShrink: 0,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            gap: 14,
            padding: 24,
            textAlign: "center",
            borderRadius: 14,
            border: dragOver
              ? "2px dashed #7c6cff"
              : "2px dashed rgba(255,255,255,0.16)",
            background: dragOver ? "rgba(124,108,255,0.08)" : "#141416",
          }}
        >
          <div style={{ opacity: 0.5 }}>
            <IconUpload size={26} />
          </div>
          <p style={{ margin: 0, fontSize: 13, lineHeight: 1.5, opacity: 0.75 }}>
            Kéo &amp; thả ảnh vào đây
            <br />
            hoặc tải ảnh mới lên
          </p>
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            disabled={uploading}
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              padding: "9px 18px",
              borderRadius: 9,
              border: "1px solid rgba(255,255,255,0.14)",
              background: uploading ? "#2a2a2e" : "#f5f5f5",
              color: uploading ? "#9a9aa0" : "#141416",
              fontSize: 13,
              fontWeight: 600,
              fontFamily: "inherit",
              cursor: uploading ? "not-allowed" : "pointer",
            }}
          >
            {uploading ? <IconSpinner size={13} /> : <IconUpload size={13} />}
            {uploading ? "Đang tải lên…" : "Upload ảnh mới"}
          </button>
          <p style={{ margin: 0, fontSize: 11, opacity: 0.4 }}>
            PNG · JPEG · WebP · GIF
          </p>
          <input
            ref={fileInputRef}
            type="file"
            accept={ACCEPT_MIME}
            style={{ display: "none" }}
            onChange={(e) => {
              const f = e.target.files?.[0];
              e.target.value = "";
              if (f) void handleFile(f);
            }}
          />
        </section>
      </div>

      {/* Close — pinned to the overlay so it never scrolls away. */}
      <button
        type="button"
        onClick={onClose}
        aria-label="Đóng"
        title="Đóng (Esc)"
        style={{ ...iconBtn(false), position: "absolute", top: 18, right: 18 }}
      >
        <IconClose size={16} />
      </button>
    </div>,
    document.body,
  );
}

function iconBtn(disabled: boolean): CSSProperties {
  return {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    padding: 0,
    borderRadius: 8,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.05)",
    color: "inherit",
    cursor: disabled ? "not-allowed" : "pointer",
    fontFamily: "inherit",
  };
}
